export const skillList = ['HTML',
'JavaScript',
'Java',
'Python',
'CSS',
'PHP',
'Angular 2/4',
'C++',
'C',
'React',
'C#',
'Objective-C',
'Go',
'Agile',
'Scrum',
'Android',
'iOS (Swift)',
'Consulting',
'Critical thinking',
'Data analysis',
'Problem-solving',
'Vue',
'Administrative',
'Business analysis',
'Business development',
'Employer Branding',
'Recruitment',
'Event Management',
'Business storytelling',
'Mongo DB',
'Editing',
'MySQL',
'Nonverbal communication',
'Presentation',
'Copywriting',
'Content management',
'Data presentation',
'Database administration',
'Middleware and integration software',
'Mobile development',
'Network and information security',
'Software engineering',
'Talent Management',
'Node.js',
'Tech support',
'UI/UX',
'Redux',
'Marketing',
'Negotiations',
'Onboarding'];
